### ISSUE TITLE
Plugin stopped working after update

### ISSUE THREAD

**Issue by sveggiani** [colinta/SublimeStringEncode#24]
Hi, StringEncode stopped working in my environment: ST 3083, OS X. Worked beautifully yersterday.

The console outputs the following:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "string_encode in /Users/sebastian/Library/Application Support/Sublime Text 3/Installed Packages/StringEncode.sublime-package", line 10, in <module>
ImportError: No module named 'stringencode'
```

Is this related to the recent updates for ST3? May be they are targeted for dev builds?

**Comment by sveggiani** [comment]
I can confirm isn't working either in latest DEV build 3087, at least in my environment.

**Comment by colinta** [comment]
Ah, verified over here.  One sec.

**Comment by colinta** [comment]
Fixed in 2.0.14 (b1e93db)?

**Comment by sveggiani** [comment]
yey! @colinta working like again now. Thank you! Great work :)

**Comment by Maschroom** [comment]
In Sublime Text 2, it still don't work. My workaround is to stop autmated updates and using a older version.

**Comment by yuheng0905** [comment]
It didn't work!  =.=|||

**Comment by yuheng0905** [comment]
It didn't work!  =.=|||

**Comment by colinta** [comment]
I downloaded Sublime Text 2 and got it to work again (v2.0.15)

**Comment by yuheng0905** [comment]
It work again! Thx

**Comment by colinta** [comment]
Cool!  Thanks for testing, everyone.  If you find another issue, please copy and paste the console output (`ctrl+backtick`)

**Comment by Maschroom** [comment]
Thanx for help. Great work. Thank you!!
