### ISSUE TITLE
[err] `AttributeError: 'module' object has no attribute 'parse'` when trying to install plugin

### ISSUE THREAD

**Issue by evandrix** [colinta/SublimeStringEncode#34]
___Stack trace___

```
reloading plugin StringEncode.string_encode
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "string_encode in /opt/sublime_text/Data/Installed Packages/StringEncode.sublime-package", line 27, in <module>
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by colinta** [comment]
That's really weird!  What version of Sublime are you using?  Can you open a console (from within Sublime - `control+backtick` on a Mac) and try importing that package:

```
import urllib.parse
quote_plus = urllib.parse.quote_plus
```
